#' Boxplots of a given GR metric
#'
#' Given a SummarizedExperiment object created by \code{\link{GRfit}},
#' this function creates boxplots according to the parameters below.
#'
#' @param fitData a SummarizedExperiment object, generated by the GRfit 
#' function.
#' @param metric the GR metric (GR50, GRinf, h_GR, GRmax, GEC50, or GR_AOC) 
#' or traditional metric (IC50, Einf, h, Emax, EC50, or AUC) that will be used  
#' for the boxplot.
#' @param groupVariable the name of the variable from data (e.g. drug,
#' cell-line, etc.) to select factors from.
#' @param pointColor a variable that defines the coloring of the points
#' overlayed on the boxplot.
#' @param factors a vector of values of "groupVariable" of data that define
#' which variables to make boxplots for. By default, a separate boxplot is made
#' for each unique value of groupVariable.
#' @param plotly a logical value indicating whether to output a ggplot2 graph
#' or an interactive ggplotly graph
#'
#' @return ggplot2 or ggplotly boxplots of the factors along the x-axis, with
#' points colored by the given variable.
#' @author Nicholas Clark
#' @details
#' Given a SummarizedExperiment object created by \code{\link{GRfit}},
#' this function creates boxplots of a given GR metric (GR50, GRmax, etc.) or 
#' traditional metric (IC50, Emax, etc.) 
#' for values of the grouping variable. The results can be viewed in a static
#' ggplot image or an interactive plotly graph.
#'
#' By default, a boxplot is created for all unique
#' values of the grouping variable. The "factors" parameter can be used to
#' specify a smaller subset of values for which to create boxplots.
#' Points are overlayed on the boxplots and
#' they can be colored by the variable specified in the pointColor parameter.
#' If pointColor is set to NULL, the points will all be black. The results can
#' be viewed in a static ggplot image or an interactive plotly graph.
#' @seealso To create the object needed for this function, see
#' \code{\link{GRfit}}. For other visualizations, see \code{\link{GRdrawDRC}}
#' and \code{\link{GRscatter}}. For online GR calculator and browser, see
#' \url{http://www.grcalculator.org}.
#' @examples
#' # Load Case A (example 1) input
#' data("inputCaseA")
#' head(inputCaseA)
#' # Run GRfit function with case = "A"
#' output1 = GRfit(inputData = inputCaseA,
#' groupingVariables = c('cell_line','agent', 'perturbation','replicate',
#' 'time'))
#' GRbox(output1, metric ='GRinf',
#' groupVariable = 'cell_line', pointColor = 'agent' , factors = c('BT20',
#' 'MCF10A'))
#' GRbox(output1, metric ='GRinf',
#' groupVariable = 'cell_line', pointColor = 'cell_line' ,
#' factors = c('BT20', 'MCF10A'), plotly = FALSE)
#' @export

GRbox <- function(fitData, metric, groupVariable, pointColor,
                  factors = "all", plotly = TRUE) {
  data = cbind(as.data.frame(SummarizedExperiment::colData(fitData)),
               t(SummarizedExperiment::assay(fitData)))
  #bottom_margin = max(nchar(data[[groupVariable]]), na.rm = TRUE)
  data[[groupVariable]] = factor(data[[groupVariable]])
  if(!identical(factors, "all")) {
    if(length(intersect(factors, data[[groupVariable]])) != length(factors)) {
      stop('Factors must be values of the grouping variable')
    }
    data = data[data[[groupVariable]] %in% factors, ]
    #bottom_margin = max(nchar(factors), na.rm = TRUE)
  }
  if(metric == "GR50") {
    data$`log10(GR50)` = log10(data$GR50)
    metric = "log10(GR50)"
  }
  if(metric == "IC50") {
    data$`log10(IC50)` = log10(data$IC50)
    metric = "log10(IC50)"
  }
  if(metric == "h_GR") {
    data$`log2(h_GR)` = log2(data$h_GR)
    metric = "log2(h_GR)"
  }
  if(metric == "h") {
    data$`log2(h)` = log2(data$h)
    metric = "log2(h)"
  }
  if(plotly == TRUE) {
    p <- ggplot2::ggplot(data, ggplot2::aes_string(x = groupVariable,
                          y = metric, text = 'experiment'))
    p = p + ggplot2::geom_boxplot(ggplot2::aes_string(fill = groupVariable,
                  alpha = 0.3), outlier.color = NA, show.legend = FALSE) +
      ggplot2::geom_jitter(width = 0.5, show.legend = FALSE,
      ggplot2::aes_string(colour = pointColor)) +
      ggplot2::xlab('') + ggplot2::ylab(metric)
    q = plotly::plotly_build(p)
    bottom_margin = max(nchar(q$layout$xaxis$ticktext), na.rm = TRUE)
    left = nchar(q$layout$xaxis$ticktext[1])
    q$layout$xaxis$tickangle = -45
    q$layout$margin$b = 15 + 6*bottom_margin
    if(left > 10) {
      left_margin = q$layout$margin$l + (left-10)*6
      q$layout$margin$l = left_margin
    }
    return(q)
  } else {
    p <- ggplot2::ggplot(data, ggplot2::aes_string(x = groupVariable,
                                                   y = metric))
    p = p + ggplot2::geom_boxplot(ggplot2::aes_string(
      fill = groupVariable, alpha = 0.3), outlier.color = NA,
      show.legend = FALSE) + ggplot2::geom_jitter(
        width = 0.5, ggplot2::aes_string(colour = pointColor)) +
      ggplot2::xlab('') + ggplot2::ylab(metric) +
      ggplot2::theme_grey(base_size = 18) +
      ggplot2::theme(axis.text.x = ggplot2::element_text(angle = 45, 
                                                         vjust = 1, hjust=1))
    return(p)
  }
}
