#' GR metrics definitions
#'
#' Given a SummarizedExperiment object created by \code{\link{GRfit}},
#' this function returns a table with the definition of each GR metric and 
#' traditional metric that is calculated.
#'
#' @param fitData a SummarizedExperiment object, generated by the GRfit 
#' function.
#'
#' @return A table of definitions of GR metrics and traditional metrics
#' @author Nicholas Clark
#' @details
#' Given a SummarizedExperiment object created by \code{\link{GRfit}},
#' this function returns a table containing the definition of each GR metric,
#' traditional metric, and goodness of fit measure in the object. 
#' This is simply a convenient accessor function, equivalent to 
#' \code{rowData(fitData)}.
#' @seealso To create the object needed for this function, see
#' \code{\link{GRfit}}.
#' @examples
#' # Load Case A (example 1) input
#' data("inputCaseA")
#' head(inputCaseA)
#' # Run GRfit function with case = "A"
#' output1 = GRfit(inputData = inputCaseA,
#' groupingVariables = c('cell_line','agent'))
#' defs = GRgetDefs(output1)
#' # See all definitions (some will be truncated)
#' \dontrun{View(defs)}
#' # See the first six descriptions
#' head(defs)
#' # Look at a specific definition
#' defs[15,]
#' @export

GRgetDefs <- function(fitData) {
  return(SummarizedExperiment::rowData(fitData))
}